### PR TITLE
BlackJack Improvements

### PR DESCRIPTION
**Pull request by ShadowNight573**
I indented the code and did some logic and typo fixes to match the rules of blackjack. Also, generalized the embed responses to prevent using the wrong terminology. I did test the code but I don't know maybe I missed something. :)

### CODE REVIEW

**Comment by Spongerooski** [comment]
>         {{if not ($embed.Get "description")}}{{dbSet .User.ID "bj" $toset}}{{end}}

        {{if not ($embed.Get "description")}}{{dbSet .User.ID "bj" $toset}}{{end}}
	{{else if reFind `\A(?i)-b(?:lack)?j(?:ack)?` .Message.Content}}usage: `-bj (bet)`

change that to this maybe? and the regex to `\A(?i)(-b(?:lack)?j(?:ack)?(?: \d+)?|hit|stand)\z`

**Comment by Spongerooski** [comment]
also 

>         {{$stick := sdict $db.Sticky}}{{dbDel .User.ID "bj"}}
        {{editMessage ($stick.Channel|toInt) ($stick.Message|toInt) (cembed $embed)}}

        {{$stick := sdict $db.Sticky}}{{dbDel .User.ID "bj"}}
        {{editMessage ($stick.Channel|toInt) ($stick.Message|toInt) (cembed $embed)}}
	{{else if reFind `\A(?i)-b(?:lack)?j(?:ack)?` .Message.Content}}{{sendMessage nil (cembed "title" "Error!" "description" "you already have a ongoing blackjack match! complete that match first" "color" $red)}}
	
that to this maybe?

**Comment by ShadowNight573** [comment]
Neither of the things you commented are things I actually changed

**Comment by ShadowNight573** [comment]
In other words, If you want to change them then merge the PR and change them yourself. :)

**Comment by Spongerooski** [comment]
no they aint i am just uh brainstorm or smt

**Comment by Spongerooski** [comment]
oh oki brb
ty for the prrrrr

**Pull request merged**
